In [ ]:
import pandas as pd

In [ ]:
#data loading
read_data= pd.read_csv('/content/nrsa1819_data_for_populationestimates.csv')

In [ ]:
#column overview
read_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1851 entries, 0 to 1850
Data columns (total 48 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   UID               1851 non-null   int64  
 1   SITE_ID           1851 non-null   object 
 2   DATE_COL          1851 non-null   object 
 3   VISIT_NO          1851 non-null   int64  
 4   SITESAMP          1851 non-null   object 
 5   UNIQUE_ID         1851 non-null   object 
 6   DSGN_CYCLE        1851 non-null   object 
 7   AG_ECO3           1851 non-null   object 
 8   AG_ECO9           1851 non-null   object 
 9   EPA_REG           1851 non-null   object 
 10  EVAL_CAT          1851 non-null   object 
 11  FED_NONFED        1851 non-null   object 
 12  FS_EW             1851 non-null   object 
 13  HUC2_NM           1851 non-null   object 
 14  LAT_DD83          1851 non-null   float64
 15  LON_DD83          1851 non-null   float64
 16  MAJ_BAS_NM        1851 non-null   object 


In [ ]:
#identify numeric columns (9)
num_column= ['UID' , 'VISIT_NO' , 'LAT_DD83', 'LON_DD83' , 'WGT_TP', 'XCOORD', 'YCOORD', 'YEAR']

In [ ]:

#dataframe overview
read_data

UID         SITE_ID    DATE_COL  VISIT_NO SITESAMP     UNIQUE_ID  \
0     2014737  NRS18_OK_10062  06/20/2018         1        Y  NRS_OK-10090   
1     2012488  NRS18_OK_10431  06/25/2018         1        Y  NRS_OK-10206   
2     2012489  NRS18_OK_10025  07/02/2018         1        Y  NRS_OK-10180   
3     2012490  NRS18_WI_10091  07/02/2018         1        Y  NRS_WI-10211   
4     2012491  NRS18_WI_10006  07/12/2018         1        Y  NRS_WI-10087   
...       ...             ...         ...       ...      ...           ...   
1846  2014722  NRS18_NC_10007  09/29/2019         1        Y  NRS_NC-10050   
1847  2014723  NRS18_KS_10027  10/07/2019         1        Y  NRS_KS-10208   
1848  2014724  NRS18_KS_10097  10/01/2019         1        Y  NRS_KS-10246   
1849  2014734  NRS18_MN_10261  10/02/2019         1        Y  NRS_MN-10220   
1850  2011534  NRS18_KS_10050  10/08/2019         1        Y  NRS_KS-10050   

     DSGN_CYCLE AG_ECO3 AG_ECO9    EPA_REG  ...          MICX_EPA_COND  \
0       2018-19  PLNLOW     SPL  Region_06  ...  At or Below Benchmark   
1       2018-19  PLNLOW     TPL  Region_06  ...  At or Below Benchmark   
2       2018-19  PLNLOW     CPL  Region_06  ...  At or Below Benchmark   
3       2018-19  PLNLOW     TPL  Region_05  ...  At or Below Benchmark   
4       2018-19  PLNLOW     UMW  Region_05  ...  At or Below Benchmark   
...         ...     ...     ...        ...  ...                    ...   
1846    2018-19   EHIGH     SAP  Region_04  ...  At or Below Benchmark   
1847    2018-19  PLNLOW     SPL  Region_07  ...  At or Below Benchmark   
1848    2018-19  PLNLOW     TPL  Region_07  ...  At or Below Benchmark   
1849    2018-19  PLNLOW     UMW  Region_05  ...  At or Below Benchmark   
1850    2018-19  PLNLOW     SPL  Region_07  ...  At or Below Benchmark   

     NTL_COND   OE_COND PTL_COND  RIPDIST_COND  RIPVEG_COND      SAL_COND  \
0        Poor   O/E<0.8     Poor           Low         Good          Good   
1        Good  O/E>=0.9     Good          High         Good          Good   
2        Good  O/E>=0.9     Good           Low         Fair          Good   
3        Poor   O/E<0.8     Poor          High         Fair  Not Assessed   
4        Good  O/E>=0.9     Good      Moderate         Good          Good   
...       ...       ...      ...           ...          ...           ...   
1846     Poor  O/E>=0.9     Poor      Moderate         Good          Good   
1847     Poor   O/E<0.8     Poor           Low         Good          Fair   
1848     Poor  O/E>=0.9     Poor           Low         Good          Good   
1849     Fair  O/E>=0.9     Fair           Low         Good          Good   
1850     Poor   O/E<0.8     Poor           Low         Good          Good   

     SALINITY_CLASS  YEAR PUBLICATION_DATE  
0        Freshwater  2018       2022-01-31  
1        Freshwater  2018       2022-01-31  
2        Freshwater  2018       2022-01-31  
3      Not Assessed  2018       2022-01-31  
4        Freshwater  2018       2022-01-31  
...             ...   ...              ...  
1846     Freshwater  2019       2022-01-31  
1847     Freshwater  2019       2022-01-31  
1848     Freshwater  2019       2022-01-31  
1849     Freshwater  2019       2022-01-31  
1850     Freshwater  2019       2022-01-31  

[1851 rows x 48 columns]

In [ ]:
#value distribution in the dataframe
read_data.nunique()

UID                 1851
SITE_ID             1851
DATE_COL             249
VISIT_NO               1
SITESAMP               1
UNIQUE_ID           1851
DSGN_CYCLE             1
AG_ECO3                3
AG_ECO9                9
EPA_REG               10
EVAL_CAT               1
FED_NONFED             2
FS_EW                  3
HUC2_NM               21
LAT_DD83            1851
LON_DD83            1851
MAJ_BAS_NM            16
MIS_BAS_NM             7
MISS_BASIN             2
OWN_NARS              11
PSTL_CODE             48
STRAH_CAT              4
URBN_NRS18             2
USFS                   2
WGT_TP               313
XCOORD              1851
YCOORD              1851
ACID_COND              4
ANC_COND               4
BEDSED_COND            4
BENT_MMI_COND          4
CYLSPER_DETECT         2
CYLSPER_EPA_COND       1
ENT_1X_STV_COND        3
FISH_MMI_COND          4
HG_COND                3
INSTRMCVR_COND         4
MICX_DETECT            2
MICX_EPA_COND          1
NTL_COND               4
OE_COND                5
PTL_COND               3
RIPDIST_COND           4
RIPVEG_COND            4
SAL_COND               4
SALINITY_CLASS         5
YEAR                   2
PUBLICATION_DATE       1
dtype: int64

In [ ]:

unique_ness = read_data.nunique()

In [ ]:
#identify the null value distribution
read_data.isnull().sum()

UID                    0
SITE_ID                0
DATE_COL               0
VISIT_NO               0
SITESAMP               0
UNIQUE_ID              0
DSGN_CYCLE             0
AG_ECO3                0
AG_ECO9                0
EPA_REG                0
EVAL_CAT               0
FED_NONFED             0
FS_EW                  0
HUC2_NM                0
LAT_DD83               0
LON_DD83               0
MAJ_BAS_NM             0
MIS_BAS_NM             0
MISS_BASIN             0
OWN_NARS               0
PSTL_CODE              0
STRAH_CAT              0
URBN_NRS18             0
USFS                   0
WGT_TP                 0
XCOORD                 0
YCOORD                 0
ACID_COND              0
ANC_COND            1840
BEDSED_COND            0
BENT_MMI_COND          0
CYLSPER_DETECT         0
CYLSPER_EPA_COND       0
ENT_1X_STV_COND        0
FISH_MMI_COND          0
HG_COND                0
INSTRMCVR_COND         0
MICX_DETECT            0
MICX_EPA_COND          0
NTL_COND               0
OE_COND                0
PTL_COND               0
RIPDIST_COND           0
RIPVEG_COND            0
SAL_COND               0
SALINITY_CLASS         0
YEAR                   0
PUBLICATION_DATE       0
dtype: int64

In [ ]:
read_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1851 entries, 0 to 1850
Data columns (total 48 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   UID               1851 non-null   int64  
 1   SITE_ID           1851 non-null   object 
 2   DATE_COL          1851 non-null   object 
 3   VISIT_NO          1851 non-null   int64  
 4   SITESAMP          1851 non-null   object 
 5   UNIQUE_ID         1851 non-null   object 
 6   DSGN_CYCLE        1851 non-null   object 
 7   AG_ECO3           1851 non-null   object 
 8   AG_ECO9           1851 non-null   object 
 9   EPA_REG           1851 non-null   object 
 10  EVAL_CAT          1851 non-null   object 
 11  FED_NONFED        1851 non-null   object 
 12  FS_EW             1851 non-null   object 
 13  HUC2_NM           1851 non-null   object 
 14  LAT_DD83          1851 non-null   float64
 15  LON_DD83          1851 non-null   float64
 16  MAJ_BAS_NM        1851 non-null   object 


In [ ]:
empt = []

In [ ]:
desired_columns = []

In [ ]:
#removing column with 1 unique value or 1851 unique value as they are of less importance
read_data.nunique()
for i in read_data.columns:
  if read_data[i].nunique()!=1:
    if read_data[i].nunique()!=1851:
      desired_columns.append(i)

In [ ]:
read_dataframe= read_data[desired_columns]

In [ ]:
#observing the unique value
read_dataframe.nunique()

DATE_COL           249
AG_ECO3              3
AG_ECO9              9
EPA_REG             10
FED_NONFED           2
FS_EW                3
HUC2_NM             21
MAJ_BAS_NM          16
MIS_BAS_NM           7
MISS_BASIN           2
OWN_NARS            11
PSTL_CODE           48
STRAH_CAT            4
URBN_NRS18           2
USFS                 2
WGT_TP             313
ACID_COND            4
ANC_COND             4
BEDSED_COND          4
BENT_MMI_COND        4
CYLSPER_DETECT       2
ENT_1X_STV_COND      3
FISH_MMI_COND        4
HG_COND              3
INSTRMCVR_COND       4
MICX_DETECT          2
NTL_COND             4
OE_COND              5
PTL_COND             3
RIPDIST_COND         4
RIPVEG_COND          4
SAL_COND             4
SALINITY_CLASS       5
YEAR                 2
dtype: int64

In [ ]:
read_dataframe

DATE_COL AG_ECO3 AG_ECO9    EPA_REG FED_NONFED     FS_EW  \
0     06/20/2018  PLNLOW     SPL  Region_06    Federal  Not_USFS   
1     06/25/2018  PLNLOW     TPL  Region_06    Federal  Not_USFS   
2     07/02/2018  PLNLOW     CPL  Region_06    Federal  Not_USFS   
3     07/02/2018  PLNLOW     TPL  Region_05    Federal  Not_USFS   
4     07/12/2018  PLNLOW     UMW  Region_05    Federal  Not_USFS   
...          ...     ...     ...        ...        ...       ...   
1846  09/29/2019   EHIGH     SAP  Region_04    Federal  Not_USFS   
1847  10/07/2019  PLNLOW     SPL  Region_07    Federal  Not_USFS   
1848  10/01/2019  PLNLOW     TPL  Region_07    Federal  Not_USFS   
1849  10/02/2019  PLNLOW     UMW  Region_05    Federal  Not_USFS   
1850  10/08/2019  PLNLOW     SPL  Region_07    Federal  Not_USFS   

                          HUC2_NM                 MAJ_BAS_NM  \
0       Arkansas-Red-White Region  Arkansas-White-Red Region   
1       Arkansas-Red-White Region  Arkansas-White-Red Region   
2       Arkansas-Red-White Region  Arkansas-White-Red Region   
3        Upper Mississippi Region   Upper Mississippi Region   
4              Great Lakes Region         Great Lakes Region   
...                           ...                        ...   
1846  South Atlantic-North Region      South-Atlantic Region   
1847        Lower Missouri Region            Missouri Region   
1848        Lower Missouri Region            Missouri Region   
1849           Great Lakes Region         Great Lakes Region   
1850        Lower Missouri Region            Missouri Region   

                       MIS_BAS_NM             MISS_BASIN  ... INSTRMCVR_COND  \
0       Arkansas-White-Red Region      Mississippi_Basin  ...           Good   
1       Arkansas-White-Red Region      Mississippi_Basin  ...           Fair   
2       Arkansas-White-Red Region      Mississippi_Basin  ...           Good   
3        Upper Mississippi Region      Mississippi_Basin  ...           Good   
4     Not Mississippi River Basin  Not_Mississippi_Basin  ...           Good   
...                           ...                    ...  ...            ...   
1846  Not Mississippi River Basin  Not_Mississippi_Basin  ...           Good   
1847        Lower Missouri Region      Mississippi_Basin  ...           Fair   
1848        Lower Missouri Region      Mississippi_Basin  ...           Poor   
1849  Not Mississippi River Basin  Not_Mississippi_Basin  ...           Good   
1850        Lower Missouri Region      Mississippi_Basin  ...           Fair   

       MICX_DETECT NTL_COND   OE_COND PTL_COND  RIPDIST_COND RIPVEG_COND  \
0     Not Detected     Poor   O/E<0.8     Poor           Low        Good   
1     Not Detected     Good  O/E>=0.9     Good          High        Good   
2     Not Detected     Good  O/E>=0.9     Good           Low        Fair   
3     Not Detected     Poor   O/E<0.8     Poor          High        Fair   
4     Not Detected     Good  O/E>=0.9     Good      Moderate        Good   
...            ...      ...       ...      ...           ...         ...   
1846  Not Detected     Poor  O/E>=0.9     Poor      Moderate        Good   
1847      Detected     Poor   O/E<0.8     Poor           Low        Good   
1848  Not Detected     Poor  O/E>=0.9     Poor           Low        Good   
1849  Not Detected     Fair  O/E>=0.9     Fair           Low        Good   
1850      Detected     Poor   O/E<0.8     Poor           Low        Good   

          SAL_COND SALINITY_CLASS  YEAR  
0             Good     Freshwater  2018  
1             Good     Freshwater  2018  
2             Good     Freshwater  2018  
3     Not Assessed   Not Assessed  2018  
4             Good     Freshwater  2018  
...            ...            ...   ...  
1846          Good     Freshwater  2019  
1847          Fair     Freshwater  2019  
1848          Good     Freshwater  2019  
1849          Good     Freshwater  2019  
1850          Good     Freshwater  2019  

[1851 rows x 34 columns]

In [ ]:
#dropped ANC_Condition since it had 1800 null values and studying it would be irrelevant
read_dataframe = read_dataframe.drop(['ANC_COND'], axis =1)
read_dataframe = read_dataframe[read_dataframe["FISH_MMI_COND"]!='Not Assessed']

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
#plt.bar(read_dataframe.isnull().sum().index  read_dataframe.isnull().sum()[0])
#plt.show()

In [ ]:
#removing entries target varaibewl value is not assessed
read_dataframe = read_dataframe[read_dataframe["FISH_MMI_COND"]!='Not Assessed']

In [ ]:
#columns that are significant
impcols = read_dataframe.columns

In [ ]:
#preparing the independent variable
X = read_dataframe.drop(['FISH_MMI_COND'], axis = 1)
X

DATE_COL AG_ECO3 AG_ECO9    EPA_REG FED_NONFED     FS_EW  \
0     06/20/2018  PLNLOW     SPL  Region_06    Federal  Not_USFS   
1     06/25/2018  PLNLOW     TPL  Region_06    Federal  Not_USFS   
3     07/02/2018  PLNLOW     TPL  Region_05    Federal  Not_USFS   
5     07/16/2018  PLNLOW     SPL  Region_06    Federal  Not_USFS   
6     07/16/2018  PLNLOW     UMW  Region_05    Federal  Not_USFS   
...          ...     ...     ...        ...        ...       ...   
1843  09/26/2019  PLNLOW     NPL  Region_08    Federal  Not_USFS   
1846  09/29/2019   EHIGH     SAP  Region_04    Federal  Not_USFS   
1847  10/07/2019  PLNLOW     SPL  Region_07    Federal  Not_USFS   
1848  10/01/2019  PLNLOW     TPL  Region_07    Federal  Not_USFS   
1850  10/08/2019  PLNLOW     SPL  Region_07    Federal  Not_USFS   

                          HUC2_NM                 MAJ_BAS_NM  \
0       Arkansas-Red-White Region  Arkansas-White-Red Region   
1       Arkansas-Red-White Region  Arkansas-White-Red Region   
3        Upper Mississippi Region   Upper Mississippi Region   
5       Arkansas-Red-White Region  Arkansas-White-Red Region   
6        Upper Mississippi Region   Upper Mississippi Region   
...                           ...                        ...   
1843        Upper Missouri Region            Missouri Region   
1846  South Atlantic-North Region      South-Atlantic Region   
1847        Lower Missouri Region            Missouri Region   
1848        Lower Missouri Region            Missouri Region   
1850        Lower Missouri Region            Missouri Region   

                       MIS_BAS_NM             MISS_BASIN  ... INSTRMCVR_COND  \
0       Arkansas-White-Red Region      Mississippi_Basin  ...           Good   
1       Arkansas-White-Red Region      Mississippi_Basin  ...           Fair   
3        Upper Mississippi Region      Mississippi_Basin  ...           Good   
5       Arkansas-White-Red Region      Mississippi_Basin  ...           Fair   
6        Upper Mississippi Region      Mississippi_Basin  ...           Fair   
...                           ...                    ...  ...            ...   
1843        Upper Missouri Region      Mississippi_Basin  ...           Poor   
1846  Not Mississippi River Basin  Not_Mississippi_Basin  ...           Good   
1847        Lower Missouri Region      Mississippi_Basin  ...           Fair   
1848        Lower Missouri Region      Mississippi_Basin  ...           Poor   
1850        Lower Missouri Region      Mississippi_Basin  ...           Fair   

       MICX_DETECT NTL_COND   OE_COND PTL_COND  RIPDIST_COND RIPVEG_COND  \
0     Not Detected     Poor   O/E<0.8     Poor           Low        Good   
1     Not Detected     Good  O/E>=0.9     Good          High        Good   
3     Not Detected     Poor   O/E<0.8     Poor          High        Fair   
5     Not Detected     Poor  O/E>=0.9     Poor      Moderate        Good   
6     Not Detected     Poor  O/E>=0.9     Poor           Low        Poor   
...            ...      ...       ...      ...           ...         ...   
1843  Not Detected     Poor    OE<0.5     Poor      Moderate        Poor   
1846  Not Detected     Poor  O/E>=0.9     Poor      Moderate        Good   
1847      Detected     Poor   O/E<0.8     Poor           Low        Good   
1848  Not Detected     Poor  O/E>=0.9     Poor           Low        Good   
1850      Detected     Poor   O/E<0.8     Poor           Low        Good   

          SAL_COND   SALINITY_CLASS  YEAR  
0             Good       Freshwater  2018  
1             Good       Freshwater  2018  
3     Not Assessed     Not Assessed  2018  
5             Fair  Slightly Saline  2018  
6             Good       Freshwater  2018  
...            ...              ...   ...  
1843          Fair       Freshwater  2019  
1846          Good       Freshwater  2019  
1847          Fair       Freshwater  2019  
1848          Good       Freshwater  2019  
1850          Good       Freshwater  2019  

[1493 rows x 32 col

In [ ]:
#preparating the target variable
y = read_dataframe['FISH_MMI_COND']

In [ ]:
#identifying the balance of different value for the target variabel
distribution = y.value_counts()

In [ ]:
#distribution = pd.DataFrame(o)

In [ ]:
distribution

FISH_MMI_COND
Poor    660
Good    479
Fair    354
Name: count, dtype: int64

In [ ]:
#Normalzing the only numeric feature
from sklearn.preprocessing import MinMaxScaler

In [ ]:
std  = MinMaxScaler()

In [ ]:
X['WGT_TP'] = std.fit_transform(X[['WGT_TP']])

In [ ]:
#checking the column past the normalization
X['WGT_TP']

0       0.039391
1       0.055084
3       0.139404
5       0.023025
6       0.028946
          ...   
1843    0.009357
1846    0.014309
1847    0.042355
1848    0.048782
1850    0.042355
Name: WGT_TP, Length: 1493, dtype: float64

In [ ]:
dataX = pd.get_dummies(X.drop(['WGT_TP'], axis =1))

In [ ]:

import numpy as np
import seaborn as sns

In [ ]:
#sns.heatmap(ui.corr() , cmap = plt.cm.gray)
#plt.show()

In [ ]:
dataX['WGT_TP'] = X['WGT_TP']

In [ ]:
import pandas as pd

In [ ]:
#numeric label encoding ofo the target
f = pd.factorize(y)
f

(array([0, 1, 1, ..., 2, 0, 2]),
 Index(['Fair', 'Good', 'Poor'], dtype='object'))

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
arf = RandomForestClassifier(n_estimators = 130)

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
x_train,x_test,y_train,y_test = train_test_split(dataX,f[0],test_size = 0.2,random_state = 40)

In [ ]:
arf.fit(x_train,y_train)


RandomForestClassifier(n_estimators=130)

In [ ]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix,ConfusionMatrixDisplay

In [ ]:
x_train

YEAR  DATE_COL_04/26/2019  DATE_COL_04/27/2019  DATE_COL_04/28/2019  \
97    2018                False                False                False   
1353  2019                False                False                False   
1752  2019                False                False                False   
763   2018                False                False                False   
1769  2019                False                False                False   
...    ...                  ...                  ...                  ...   
1256  2019                False                False                False   
202   2018                False                False                False   
11    2018                False                False                False   
263   2018                False                False                False   
1676  2019                False                False                False   

      DATE_COL_04/29/2019  DATE_COL_04/30/2019  DATE_COL_05/01/2019  \
97                  False                False                False   
1353                False                False                False   
1752                False                False                False   
763                 False                False                False   
1769                False                False                False   
...                   ...                  ...                  ...   
1256                False                False                False   
202                 False                False                False   
11                  False                False                False   
263                 False                False                False   
1676                False                False                False   

      DATE_COL_05/02/2019  DATE_COL_05/06/2019  DATE_COL_05/07/2019  ...  \
97                  False                False                False  ...   
1353                False                False                False  ...   
1752                False                False                False  ...   
763                 False                False                False  ...   
1769                False                False                False  ...   
...                   ...                  ...                  ...  ...   
1256                False                False                False  ...   
202                 False                False                False  ...   
11                  False                False                False  ...   
263                 False                False                False  ...   
1676                False                False                False  ...   

      RIPVEG_COND_Poor  SAL_COND_Fair  SAL_COND_Good  SAL_COND_Not Assessed  \
97                True          False           True                  False   
1353             False          False           True                  False   
1752              True          False           True                  False   
763               True          False          False                  False   
1769              True          False           True                  False   
...                ...            ...            ...                    ...   
1256             False          False          False                  False   
202              False          False           True                  False   
11                True          False           True                  False   
263              False          False           True                  False   
1676              True          False           True                  False   

      SAL_COND_Poor  SALINITY_CLASS_Freshwater  \
97            False                       True   
1353          False                       True   
1752          False                       True   
763            True                      False   
1769          False                       True   
...             ...                        ...   
1256           T

In [ ]:
result_y = arf.predict(x_test)

In [ ]:
accuracy_score(result_y  , y_test)

0.6287625418060201

In [ ]:
precision_score(y_test, result_y,average = None)

array([0.48      , 0.64      , 0.64367816])

In [ ]:
recall_score(y_test , result_y, average =None)

array([0.19354839, 0.65306122, 0.8057554 ])

In [ ]:
confusion_matrix(y_test, result_y)

array([[ 12,  18,  32],
       [  4,  64,  30],
       [  9,  18, 112]])

In [ ]:
184/299

0.6153846153846154

In [ ]:
from sklearn.svm import SVC
scv = SVC(C=1,kernel = 'rbf')

In [ ]:
scv.fit(x_train,y_train)

SVC(C=1)

In [ ]:
result__y = scv.predict(x_test)

In [ ]:
accuracy_score(y_test , result__y)

0.46488294314381273

In [ ]:
precision_score(y_test , result__y,average = None)

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


array([0.        , 0.        , 0.46488294])

In [ ]:
recall_score(y_test, result__y, average = None)

array([0., 0., 1.])

In [ ]:
f1_score(y_test , result__y, average = None)

array([0.       , 0.       , 0.6347032])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier()

In [ ]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
yy = knn.predict(x_test)

In [ ]:
accuracy_score(y_test , yy)

0.5618729096989966

In [ ]:
recall_score(y_test , yy , average = None)

array([0.33870968, 0.65306122, 0.5971223 ])

In [ ]:
precision_score(y_test , yy, average = None)

array([0.30434783, 0.57142857, 0.70338983])

In [ ]:
f1_score(y_test , yy, average  = None)

array([0.32061069, 0.60952381, 0.6459144 ])

In [ ]:
confusion_matrix(y_test , yy)

array([[21, 22, 19],
       [18, 64, 16],
       [30, 26, 83]])

In [ ]:

from sklearn.tree import DecisionTreeClassifier
dcc = DecisionTreeClassifier()

In [ ]:
dcc.fit(x_train , y_train)

DecisionTreeClassifier()

In [ ]:
y_rest = dcc.predict(x_test)

In [ ]:
accuracy_score(y_test , y_rest)

0.5150501672240803

In [ ]:
precision_score(y_test , y_rest, average = None)

array([0.2625    , 0.57608696, 0.62992126])

In [ ]:
recall_score(y_test , y_rest, average = None)

array([0.33870968, 0.54081633, 0.57553957])

In [ ]:
f1_score(y_test , y_rest, average = None)

array([0.29577465, 0.55789474, 0.60150376])

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
confusion_matrix(y_test , y_rest)

array([[21, 15, 26],
       [24, 53, 21],
       [35, 24, 80]])

In [ ]:
lgr = LogisticRegression()

In [ ]:
lgr.fit(x_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
yy_t= lgr.predict(x_test)

In [ ]:
print(accuracy_score(y_test, yy_t))
print(recall_score(y_test, yy_t,average = None))


0.5986622073578596
[0.19354839 0.6122449  0.76978417]


In [ ]:
precision_score(y_test , yy_t, average = None)
f1_score(y_test, yy_t, average = None)

array([0.25531915, 0.60606061, 0.69934641])

In [ ]:
confusion_matrix(y_test, yy_t)

array([[ 12,  22,  28],
       [  6,  60,  32],
       [ 14,  18, 107]])

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)
gb = GradientBoostingClassifier(n_estimators=100, random_state=42)
lr = LogisticRegression(max_iter=1000)
svc = SVC(probability=True, kernel='rbf', random_state=42)

In [ ]:
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import StackingClassifier

In [ ]:
voting_soft = VotingClassifier(
    estimators=[('rf', rf), ('gb', gb), ('lr', lr), ('svc', svc)],
    voting='soft'
)

In [ ]:
# Hard voting
voting_hard = VotingClassifier(
    estimators=[('rf', rf), ('gb', gb), ('lr', lr), ('svc', svc)],
    voting='hard'
)

In [ ]:
voting_weighted = VotingClassifier(
    estimators=[('rf', rf), ('gb', gb), ('lr', lr), ('svc', svc)],
    voting='soft',
    weights=[2, 2, 1, 1]
)

In [ ]:
stack = StackingClassifier(
    estimators=[('rf', rf), ('gb', gb), ('svc',svc)],
    final_estimator=LogisticRegression(),
    passthrough=True
)

In [ ]:
models = {'voting_soft': voting_soft,'voting_hard': voting_hard,'voting_weighted':voting_weighted, 'stack':stack}

In [ ]:
for name, model in models.items():
  model.fit(x_train,y_train)
  y_pred = model.predict(x_test)
  acc = accuracy_score(y_test,y_pred)
  print(acc)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.6220735785953178


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.6254180602006689


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.6254180602006689


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.5986622073578596


In [ ]:
#randomforestclassifier cm
sns.heatmap(confusion_matrix(y__test, y_test), xticklabels = ['Fair','Good','Poor'], yticklabels = ['Fair','Good','Poor'], annot = True, fmt = 'g' )
plt.show()

In [ ]:

sns.heatmap(confusion_matrix(y_test, y__test) , xticklabels=['Fair','Good','Poor'], yticklabels = ['Fair','Good','Poor'])

In [ ]:
sns.heatmap(knn_matrix, xticklabels = ['Fair', 'Good', 'Poor'], yticklabels = ['Fair','Good','Poor'], annot = True)
plt.xlabel("Predcited_Value")
plt.ylabel("Real_Value")
plt.show()

In [ ]:
newcm  = confusion_matrix(y_test, yy_test)

In [ ]:
sns.heatmap(newcm, xticklabels= ['Fair', 'Good', 'Poor'], yticklabels = ['Fair', 'Good','Poor'], annot = True)
plt.xlabel("Model Value")
plt.ylabel("Actual Value")
plt.title("The Prediction of o vector classifier")
plt.show()

In [ ]:
#import joblib

In [ ]:
#joblib.dump(rf, 'kbc.pkl')

In [ ]:
#from sklearn.metrics import accuracy_score